### ISSUE TITLE
terminal too small error

### ISSUE THREAD

**Issue by ZeroQLi** [pryme-svg/periodic-table-tui#4]
noob github user here, it shows me an error while running the client, 
Terminal: kitty (however it doesn't work in any of the installed terminals)
![image](https://user-images.githubusercontent.com/71174337/141809704-599a6a56-0ba8-4e05-a838-465ccc0c441c.png)

just let me know if you want any more info

**Comment by wlmchen** [comment]
did you try increasing the size of the terminal by dragging the edge?

**Comment by ZeroQLi** [comment]
yup, it still hows me the same error, i've tried on different terminals and still got the same result, i'm using gnome 3.38 on ubuntu 20.04.

update: ok seems to be an issue with kitty only. the other terminals work fine. i'm really not sure how to troubleshoot this problem, the arrow still doesn't budge even though ive set to fullscreen
![image](https://user-images.githubusercontent.com/71174337/141982985-562655eb-2c36-46ab-bd0b-249a2b5c7beb.png)

**Comment by wlmchen** [comment]
Unfortunately I cannot reproduce this bug as shown in the video below

https://user-images.githubusercontent.com/65417452/142057257-fec52561-b351-4e9e-bd01-6bafe9f3fce1.mp4
