### ISSUE TITLE
ImportError while trying to run   __main__.py

### ISSUE THREAD

**Issue by showoi** [pryme-svg/periodic-table-tui#5]
File "C:\Users\cikimo\Downloads\periodic-table-tui-master\periodic_table_tui\__main__.py", line 5, in <module>
    from .periodic_table import periodicTable
ImportError: attempted relative import with no known parent package

**Comment by wlmchen** [comment]
The script isn't meant to be run directly, rather as a module.
Try `python -m periodic_table_tui` in the root of the repository

**Comment by wlmchen** [comment]
I've added a snippet that allows you to run it without the package context.

You should be able to run `periodic_table.py` without issue now
